Fully upgrading to Swift 4
Note: On Swift 4, Linux MUST explicitly declare `import Dispatch`
otherwise it will yield “undefined reference to
'_NSConcreteStackBlock’”, etc.